server.port: 9000

spring:
  codec:
    max-in-memory-size: 100MB
  cloud:
    stream:
      kafka:
        binder:
          brokers: "${KAFKA_BROKER_HOST}"
          auto-add-partitions: false
          auto-create-topics: false
          producer-properties:
            acks: "all"
            retries: 3
            enable.idempotence: "true"
      bindings:
        output:
          destination: "smartpoke-device-presence"
        sensor-settings-output:
          destination: "smartpoke-sensor-settings"


app.meraki.secret: "${MERAKI_SECRET:abcd}"

management:
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: metrics, health, prometheus
