server.port: 9000
spring.cloud.stream:
  kafka:
    binder:
      brokers: "${KAFKA_BROKER_HOST}"
  bindings:
    output:
      destination: "${KAFKA_TOPIC}"

app.meraki.secret: "${MERAKI_SECRET:abcd}"