server.port: 9000
spring.cloud.stream:
  kafka:
    binder:
      brokers: "${KAFKA_BROKER_HOST}"
      producer-properties:
        acks: "all"
        retries: 3
        enable.idempotence: "true"
  bindings:
    output:
      destination: "smartpoke-device-presence"

app.meraki.secret: "${MERAKI_SECRET:abcd}"