{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "access-point-incoming-endpoint.serviceAccountName" . }}
  labels:
{{ include "access-point-incoming-endpoint.labels" . | nindent 4 }}
{{- end -}}
